version: "3"
services:
  api:
    build:
      context: .
    container_name: wemo_api
    restart: always
    depends_on:
      - postgre
    # ports:
    #   - 3000:3000
    networks:
      - devops
  postgre:
    container_name: wemo_postgis
    image: postgis/postgis:14-3.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - TZ=$TZ
      - PGTZ=$PGTZ
    volumes:
      - ./data:/data/db
    ports:
      - 5432:5432
    networks:
      - devops

networks:
  devops:
    external: true